spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: vaemin
    password: password
    url: jdbc:mysql://localhost:3306/vaemin
